apiVersion: v1
kind: Namespace
metadata:
  name: sample-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namegen
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namegen
  template:
    metadata:
      labels:
        app: namegen
        tier: backend
    spec:
      containers:
        - name: namegen
          livenessProbe:
            httpGet:
              path: /
              port: 5004
            initialDelaySeconds: 30
            periodSeconds: 120
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 5004
            initialDelaySeconds: 10
            periodSeconds: 120
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          image: zerofai/app-namegen:202404211620
          env:
          - name: dbHost
            value: "dbhost:3306"
          - name: username
            valueFrom:
              secretKeyRef:
                name: namegen-secret
                key: username
          - name: password
            valueFrom:
              secretKeyRef:
                name: namegen-secret
                key: password
          ports:
            - containerPort: 5004
---
apiVersion: v1
kind: Service
metadata:
  name: namegen
  namespace: sample-app
  labels:
    app: namegen
spec:
  ports:
    - port: 5003
  selector:
    app: namegen
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
        tier: backend
    spec:
      containers:
        - name: image
          livenessProbe:
            httpGet:
              path: /
              port: 5003
            initialDelaySeconds: 30
            periodSeconds: 120
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 5003
            initialDelaySeconds: 10
            periodSeconds: 120
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          image: zerofai/app-image:202404211629
          env:
          - name: S3_URL
            value: https://minio_url
          - name: S3_BUCKET
            value: demo-image
          - name: aws_access_key
            valueFrom:
              secretKeyRef:
                name: image-secret
                key: aws_access_key
          - name: aws_secret_key
            valueFrom:
              secretKeyRef:
                name: image-secret
                key: aws_secret_key
          ports:
            - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: image
  namespace: sample-app
  labels:
    app: image
spec:
  ports:
    - port: 5003
  selector:
    app: image
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
        tier: backend
    spec:
      containers:
        - name: greeting
          livenessProbe:
            httpGet:
              path: /
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 120
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 120
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          image: zerofai/app-greeting:202404091603
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: greeting
  namespace: sample-app
  labels:
    app: greeting
spec:
  ports:
    - port: 5001
  selector:
    app: greeting
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
        tier: backend
    spec:
      containers:
        - name: weather
          livenessProbe:
            httpGet:
              path: /
              port: 5002
            initialDelaySeconds: 30
            periodSeconds: 120
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 120
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          image: zerofai/app-weather:202404101041
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: weather
  namespace: sample-app
  labels:
    app: weather
spec:
  ports:
    - port: 5002
  selector:
    app: weather
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
        tier: frontend
    spec:
      containers:
        - name: ui
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 120
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 120
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          image: zerofai/app-ui:202404091552
          env:
          - name: GREETING_HOSTNAME
            value: greeting:5001
          - name: WEATHER_HOSTNAME
            value: weather:5002
          - name: IMAGE_HOSTNAME
            value: image:5003
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: sample-app
  labels:
    app: ui
spec:
  ports:
    - port: 5000
      nodePort: 30030
  selector:
    app: ui
    tier: frontend
  type: NodePort